#!/usr/bin/env python3
"""T08 -- THE RULE'S MEASURED PHYSICS.  Statement: the Fibonacci chain built from the rule sigma (a hopping/onsite
sequence following the fixed point of a->ab, b->a) has a spectrum whose gaps are labelled by the integrated density of
states N(E) in (Z + Z/phi) mod 1 (gap-labelling theorem; observed in photonic, polaritonic and cold-atom chains); the
spectrum is the set of energies whose transfer-matrix trace orbit stays bounded, and that trace orbit is generated by the
rule's own Fricke action (x, y, z) -> (z, x, xz - y) from T03/T04, with the Fricke invariant conserved exactly.
Comparison class: the four rules of the K4-orbit (T01) -- all give the same label set; the four-letter rule of the
record does not.  The scale (hopping, lattice spacing) is the experimenter's: axiom A7."""
import numpy as np
from scipy.linalg import eigh_tridiagonal
from _common import say, write
PHI = (1 + 5 ** .5) / 2
def fixed_point(rule, seed, n):
    w = seed
    for _ in range(n): w = ''.join(rule[c] for c in w)
    return w
def spectrum(word, ta=1.0, tb=0.6, N=None):
    hop = np.array([ta if c == 'a' else tb for c in word])[:N]
    d = np.zeros(len(hop) + 1); e = hop
    return eigh_tridiagonal(d, e, eigvals_only=True)
def gap_labels(ev, n_gaps=12, ncand=40):
    ev = np.sort(ev); N = len(ev); gaps = np.diff(ev); order = np.argsort(gaps)[::-1][:n_gaps]
    out = []
    for i in sorted(order):
        ids = (i + 1) / N
        best = min(((abs(((n / PHI) % 1) - ids), n) for n in range(-ncand, ncand + 1)), key=lambda t: t[0])
        out.append((round(float(ev[i]), 5), round(float(ev[i + 1]), 5), round(ids, 6), best[1], round(best[0], 6)))
    return out
R = {'a': 'ab', 'b': 'a'}
w = fixed_point(R, 'a', 19)           # length F_21 = 10946
ev = spectrum(w)
labels = gap_labels(ev)
say(f"Fibonacci chain, {len(w)+1} sites, hoppings t_a=1, t_b=0.6: {len(ev)} levels; bandwidth [{ev.min():.4f}, {ev.max():.4f}]")
say("largest 12 gaps: (E_low, E_high, IDS, integer n with IDS = n/phi mod 1, residual)")
for row in labels: say("   ", row)
maxres = max(r[4] for r in labels)
say(f"max residual of the labels over the 12 largest gaps: {maxres:.2e}  (finite-size: ~1/N = {1/len(ev):.1e})")
# comparison class: the K4-orbit rules give the same label set; the four-letter rule does not
def rev(rule): return {k: v[::-1] for k, v in rule.items()}
def swap(rule):
    s = lambda t: t.translate(str.maketrans('ab', 'ba')); return {s(k): s(v) for k, v in rule.items()}
orbit = {'id': R, 'rev': rev(R), 'swap': swap(R), 'revswap': rev(swap(R))}
same = {}
for name, rule in orbit.items():
    seed = 'a' if 'a' in rule and rule['a'].startswith('a') or name in ('id', 'rev') else 'b'
    ww = fixed_point(rule, seed, 19)
    if len(ww) < 5000: ww = fixed_point(rule, seed, 20)
    ev2 = spectrum(ww, N=len(w)); l2 = gap_labels(ev2)
    same[name] = (bool(max(r[4] for r in l2) < 3 / len(ev2)), float(max(r[4] for r in l2)))
say(f"K4-orbit rules: gap labels in Z + Z/phi within 3/N (fits?, max residual): {same}")
R4 = {'a': 'abAAB', 'b': 'aAB', 'A': 'abAB', 'B': 'aA'}
w4 = fixed_point(R4, 'a', 8)
hop4 = {'a': 1.0, 'b': 0.6, 'A': 0.8, 'B': 0.4}
ev4 = eigh_tridiagonal(np.zeros(len(w4) + 1), np.array([hop4[c] for c in w4]), eigvals_only=True)
l4 = gap_labels(ev4)
say(f"four-letter rule ({len(w4)+1} sites): max residual against Z + Z/phi labels = {max(r[4] for r in l4):.3f} (should NOT fit)")
# the trace map: transfer matrices for the words sigma^n(a) satisfy M_{n+1} = M_n M_{n-1}; their traces obey the
# Fricke action of the rule, and the Fricke invariant is conserved
def T(t, E): return np.array([[E / t, -1.0], [1.0, 0.0]])
E0 = 0.3; ta, tb = 1.0, 0.6
Ma, Mb = T(ta, E0), T(tb, E0)                     # transfer matrices for letters a and b
x, y, z = np.trace(Ma), np.trace(Mb), np.trace(Ma @ Mb)
kappa = x * x + y * y + z * z - x * y * z
# the rule sends (a, b) -> (ab, a): traces (x, y, z) -> (z, x, tr(ab a)) = (z, x, xz - y)
words = ['a', 'ab']
mats = [Ma, Ma @ Mb]
tr_seq = [np.trace(m) for m in mats]
for k in range(12):
    words.append(words[-1] + words[-2]); mats.append(mats[-1] @ mats[-2]); tr_seq.append(np.trace(mats[-1]))
fricke = [x]; cur = (x, y, z)
for k in range(13):
    cur = (cur[2], cur[0], cur[0] * cur[2] - cur[1]); fricke.append(cur[0])
# fricke[k] is the trace of the transfer matrix of the word sigma^k(a): check against the matrix products
ok_trace = np.allclose(tr_seq[:13], fricke[:13], atol=1e-6)
cur = (x, y, z); kaps = [kappa]
for k in range(12):
    cur = (cur[2], cur[0], cur[0] * cur[2] - cur[1]); kaps.append(cur[0] ** 2 + cur[1] ** 2 + cur[2] ** 2 - cur[0] * cur[1] * cur[2])
say(f"trace of the transfer matrix of sigma^k(a), k=0..12, equals the rule's Fricke orbit (z, x, xz-y): {ok_trace}")
say(f"Fricke invariant along the orbit: {kaps[0]:.12f}, spread {max(kaps)-min(kaps):.2e}  (conserved: the KKT invariant of the Fibonacci chain)")
write('T08', dict(sites=len(w) + 1, labels=labels, max_label_residual=maxres, k4_same=same, four_letter_max_residual=max(r[4] for r in l4),
                  trace_map_matches_fricke=bool(ok_trace), fricke_invariant=float(kappa), fricke_spread=float(max(kaps) - min(kaps))))
