#!/usr/bin/env python3
"""T13b -- THE METALLIC BUNDLES' TRACE FIELDS FROM THEIR OWN HOLONOMY.  Statement: for the once-punctured-torus bundles
with monodromy R^m L^m (m = 1..4; m = 1 is m004), SnapPy's high-precision holonomy gives the traces of the group
generators; their minimal polynomials over Q (integer relations at ~60 digits) give the trace field degree per m, and
the field generated by squares of traces (the invariant trace field) is identified for m = 1, 2.  This is the
independent route that decides which of T13's rule-side fixed points is the geometric one.  Comparison class: m = 1..4."""
import snappy, mpmath as mp
from snappy import pari
from _common import say, write
pari.set_real_precision(60)
def minpoly_pari(w, maxdeg=12):
    for d in range(1, maxdeg + 1):
        rel = pari.lindep([w ** i for i in range(d + 1)])
        if len(rel) < d + 1: continue
        rel = [int(rel[i]) for i in range(d + 1)]
        if rel[d] == 0 or max(abs(c) for c in rel) > 10**9: continue
        if rel[d] < 0: rel = [-c for c in rel]
        val = sum(pari(c) * w ** i for i, c in enumerate(rel))
        if abs(complex(val)) < 1e-40: return rel
    return None
out = {}
for m in range(1, 5):
    name = 'b++' + 'R' * m + 'L' * m
    M = snappy.Manifold(name)
    iso = M.is_isometric_to(snappy.Manifold('m004')) if m == 1 else None
    H = M.high_precision(); G = H.fundamental_group()
    gens = G.generators()
    traces = {}
    words = list(gens) + [gens[0] + gens[1]] + ([gens[0] + gens[2], gens[1] + gens[2]] if len(gens) > 2 else [])
    for wd in words:
        Mx = G.SL2C(wd); t = Mx[0, 0] + Mx[1, 1]
        tp = t.gen() if hasattr(t, 'gen') else pari(str(t))
        traces[wd] = (complex(t), minpoly_pari(tp), minpoly_pari(tp * tp))
    degs = sorted({len(v[1]) - 1 for v in traces.values() if v[1]})
    degs2 = sorted({len(v[2]) - 1 for v in traces.values() if v[2]})
    out[m] = dict(name=name, generators=len(gens), volume=float(M.volume()), homology=str(M.homology()),
                  trace_minpolys={w: v[1] for w, v in traces.items()}, square_minpolys={w: v[2] for w, v in traces.items()},
                  trace_degrees=degs, square_degrees=degs2, is_m004=(bool(iso) if iso is not None else None))
    say(f"m={m} {name}: gens {len(gens)}, vol {float(M.volume()):.6f}, H1 {M.homology()}" + (f", is m004: {iso}" if iso is not None else ""))
    for w, v in traces.items():
        say(f"    tr({w}) = {v[0]:.6f}: minpoly {v[1]}; minpoly of its square {v[2]}")
    say(f"    degrees of trace minpolys {degs}; of squared traces {degs2}")
write('T13b', {str(k): v for k, v in out.items()})

# --- the closing identity: for each m the minimal polynomial of the bundle's fibre-generator trace equals a factor of
# the rule-side Markoff intersection (T13).  (The triple itself is a fixed point of F_m^2 only in the basis in which the
# rule acts as a -> a^m b, b -> a; SnapPy's fibre basis differs by an automorphism for m = 3, 4, so the field identity,
# which is basis-independent, is the right statement.)
import json, os
T13 = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'out', 'T13.json'))) if os.path.exists(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'out', 'T13.json')) else None
match = {}
for m in range(1, 5):
    polys = [v for v in out[m]['trace_minpolys'].values() if v and len(v) > 2]
    rule = T13['geometric'][str(m)] if T13 else None
    import sympy as sp
    X = sp.symbols('x')
    ok = any(sp.expand(sum(c * X**i for i, c in enumerate(pl)) - sp.sympify(rule)) == 0 for pl in polys) if rule else None
    match[m] = ok
    say(f"m={m}: a SnapPy fibre-trace minimal polynomial equals the rule-side geometric polynomial: {ok}")
write('T13b_closing', {str(k): v for k, v in match.items()})
